[tool.ruff]
line-length = 88
target-version = "py312"  # Adjust to your Python version
fix = true
show-fixes = true

# Enable these rule categories
lint.select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "W",   # pycodestyle warnings
    "I",   # isort
    "N",   # pep8-naming
    "D",   # pydocstyle
    "UP",  # pyupgrade
    "C90", # mccabe (complexity)
    "B",   # flake8-bugbear
    "TID", # tidy imports
    "SIM", # flake8-simplify
]

# Example of ignored rules (adjust as needed)
lint.ignore = [
    "D100",  # Missing docstring in public module
    "D104",  # Missing docstring in public package
    "D107",  # Missing docstring in __init__
    "D103", #Missing docstring in public function   
    "B008",
    "D203",
    "D213",
]

# Exclude common folders
exclude = [
    ".git",
    ".venv",
    "__pycache__"
]

# Optional: Set per-file ignores (e.g., ignore specific rules in tests)
[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D"]
